package com.generation.beans;
// Generated 24/09/2018 11:42:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CorrectAnswer generated by hbm2java
 */
public class CorrectAnswer  implements java.io.Serializable {


     private int idcorrectAnwser;
     private String answerCorrect;
     private Integer correctAnswerStatus;
     private Set questions = new HashSet(0);

    public CorrectAnswer() {
    }

	
    public CorrectAnswer(int idcorrectAnwser) {
        this.idcorrectAnwser = idcorrectAnwser;
    }
    public CorrectAnswer(int idcorrectAnwser, String answerCorrect, Integer correctAnswerStatus, Set questions) {
       this.idcorrectAnwser = idcorrectAnwser;
       this.answerCorrect = answerCorrect;
       this.correctAnswerStatus = correctAnswerStatus;
       this.questions = questions;
    }
   
    public int getIdcorrectAnwser() {
        return this.idcorrectAnwser;
    }
    
    public void setIdcorrectAnwser(int idcorrectAnwser) {
        this.idcorrectAnwser = idcorrectAnwser;
    }
    public String getAnswerCorrect() {
        return this.answerCorrect;
    }
    
    public void setAnswerCorrect(String answerCorrect) {
        this.answerCorrect = answerCorrect;
    }
    public Integer getCorrectAnswerStatus() {
        return this.correctAnswerStatus;
    }
    
    public void setCorrectAnswerStatus(Integer correctAnswerStatus) {
        this.correctAnswerStatus = correctAnswerStatus;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


