package com.generation.beans;
// Generated 24/09/2018 11:42:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private Integer idModule;
     private String nombreModule;
     private Integer moduleStatus;
     private Set topics = new HashSet(0);

    public Module() {
    }

    public Module(String nombreModule, Integer moduleStatus, Set topics) {
       this.nombreModule = nombreModule;
       this.moduleStatus = moduleStatus;
       this.topics = topics;
    }
   
    public Integer getIdModule() {
        return this.idModule;
    }
    
    public void setIdModule(Integer idModule) {
        this.idModule = idModule;
    }
    public String getNombreModule() {
        return this.nombreModule;
    }
    
    public void setNombreModule(String nombreModule) {
        this.nombreModule = nombreModule;
    }
    public Integer getModuleStatus() {
        return this.moduleStatus;
    }
    
    public void setModuleStatus(Integer moduleStatus) {
        this.moduleStatus = moduleStatus;
    }
    public Set getTopics() {
        return this.topics;
    }
    
    public void setTopics(Set topics) {
        this.topics = topics;
    }




}


