package com.generation.beans;
// Generated 9/09/2018 04:34:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Modules generated by hbm2java
 */
public class Modules  implements java.io.Serializable {


     private Integer idModule;
     private String nombreModule;
     private Set topicses = new HashSet(0);

    public Modules() {
    }

    public Modules(String nombreModule, Set topicses) {
       this.nombreModule = nombreModule;
       this.topicses = topicses;
    }
   
    public Integer getIdModule() {
        return this.idModule;
    }
    
    public void setIdModule(Integer idModule) {
        this.idModule = idModule;
    }
    public String getNombreModule() {
        return this.nombreModule;
    }
    
    public void setNombreModule(String nombreModule) {
        this.nombreModule = nombreModule;
    }
    public Set getTopicses() {
        return this.topicses;
    }
    
    public void setTopicses(Set topicses) {
        this.topicses = topicses;
    }

    @Override
    public String toString() {
        return "Modules{" + "idModule=" + idModule + ", nombreModule=" + nombreModule + ", topicses=" + topicses + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.idModule);
        hash = 89 * hash + Objects.hashCode(this.nombreModule);
        hash = 89 * hash + Objects.hashCode(this.topicses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Modules other = (Modules) obj;
        if (!Objects.equals(this.nombreModule, other.nombreModule)) {
            return false;
        }
        if (!Objects.equals(this.idModule, other.idModule)) {
            return false;
        }
        if (!Objects.equals(this.topicses, other.topicses)) {
            return false;
        }
        return true;
    }

    

}


