package com.generation.beans;
// Generated 8/09/2018 07:09:43 PM by Hibernate Tools 4.3.1



/**
 * QuestionsHasUsersId generated by hbm2java
 */
public class QuestionsHasUsersId  implements java.io.Serializable {


     private int questionsIdQuestion;
     private int questionsTopicsIdTopic;
     private int questionsTopicsModulesIdModule;
     private int usersIdUser;

    public QuestionsHasUsersId() {
    }

    public QuestionsHasUsersId(int questionsIdQuestion, int questionsTopicsIdTopic, int questionsTopicsModulesIdModule, int usersIdUser) {
       this.questionsIdQuestion = questionsIdQuestion;
       this.questionsTopicsIdTopic = questionsTopicsIdTopic;
       this.questionsTopicsModulesIdModule = questionsTopicsModulesIdModule;
       this.usersIdUser = usersIdUser;
    }
   
    public int getQuestionsIdQuestion() {
        return this.questionsIdQuestion;
    }
    
    public void setQuestionsIdQuestion(int questionsIdQuestion) {
        this.questionsIdQuestion = questionsIdQuestion;
    }
    public int getQuestionsTopicsIdTopic() {
        return this.questionsTopicsIdTopic;
    }
    
    public void setQuestionsTopicsIdTopic(int questionsTopicsIdTopic) {
        this.questionsTopicsIdTopic = questionsTopicsIdTopic;
    }
    public int getQuestionsTopicsModulesIdModule() {
        return this.questionsTopicsModulesIdModule;
    }
    
    public void setQuestionsTopicsModulesIdModule(int questionsTopicsModulesIdModule) {
        this.questionsTopicsModulesIdModule = questionsTopicsModulesIdModule;
    }
    public int getUsersIdUser() {
        return this.usersIdUser;
    }
    
    public void setUsersIdUser(int usersIdUser) {
        this.usersIdUser = usersIdUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionsHasUsersId) ) return false;
		 QuestionsHasUsersId castOther = ( QuestionsHasUsersId ) other; 
         
		 return (this.getQuestionsIdQuestion()==castOther.getQuestionsIdQuestion())
 && (this.getQuestionsTopicsIdTopic()==castOther.getQuestionsTopicsIdTopic())
 && (this.getQuestionsTopicsModulesIdModule()==castOther.getQuestionsTopicsModulesIdModule())
 && (this.getUsersIdUser()==castOther.getUsersIdUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQuestionsIdQuestion();
         result = 37 * result + this.getQuestionsTopicsIdTopic();
         result = 37 * result + this.getQuestionsTopicsModulesIdModule();
         result = 37 * result + this.getUsersIdUser();
         return result;
   }   


}


