package com.generation.beans;
// Generated 24/09/2018 11:42:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer idQuestion;
     private Subtopic subtopic;
     private String question;
     private Integer questionStatus;
     private Set correctAnswers = new HashSet(0);
     private Set users = new HashSet(0);
     private Set wrongAnswers = new HashSet(0);

    public Question() {
    }

	
    public Question(Subtopic subtopic) {
        this.subtopic = subtopic;
    }
    public Question(Subtopic subtopic, String question, Integer questionStatus, Set correctAnswers, Set users, Set wrongAnswers) {
       this.subtopic = subtopic;
       this.question = question;
       this.questionStatus = questionStatus;
       this.correctAnswers = correctAnswers;
       this.users = users;
       this.wrongAnswers = wrongAnswers;
    }
   
    public Integer getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(Integer idQuestion) {
        this.idQuestion = idQuestion;
    }
    public Subtopic getSubtopic() {
        return this.subtopic;
    }
    
    public void setSubtopic(Subtopic subtopic) {
        this.subtopic = subtopic;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public Integer getQuestionStatus() {
        return this.questionStatus;
    }
    
    public void setQuestionStatus(Integer questionStatus) {
        this.questionStatus = questionStatus;
    }
    public Set getCorrectAnswers() {
        return this.correctAnswers;
    }
    
    public void setCorrectAnswers(Set correctAnswers) {
        this.correctAnswers = correctAnswers;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getWrongAnswers() {
        return this.wrongAnswers;
    }
    
    public void setWrongAnswers(Set wrongAnswers) {
        this.wrongAnswers = wrongAnswers;
    }




}


