package com.generation.beans;
// Generated 8/09/2018 07:09:43 PM by Hibernate Tools 4.3.1



/**
 * QuestionsHasUsers generated by hbm2java
 */
public class QuestionsHasUsers  implements java.io.Serializable {


     private QuestionsHasUsersId id;

    public QuestionsHasUsers() {
    }

    public QuestionsHasUsers(QuestionsHasUsersId id) {
       this.id = id;
    }
   
    public QuestionsHasUsersId getId() {
        return this.id;
    }
    
    public void setId(QuestionsHasUsersId id) {
        this.id = id;
    }




}


