package com.generation.beans;
// Generated 8/09/2018 07:09:43 PM by Hibernate Tools 4.3.1



/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private Integer idQuestion;
     private String question;
     private String answer1;
     private String answer2;
     private String answer3;
     private String answer4;
     private Boolean correctAnswer;
     private int topicsIdTopic;
     private int topicsModulesIdModule;
     private int subtopicsIdsubtopics;

    public Questions() {
    }

	
    public Questions(int topicsIdTopic, int topicsModulesIdModule, int subtopicsIdsubtopics) {
        this.topicsIdTopic = topicsIdTopic;
        this.topicsModulesIdModule = topicsModulesIdModule;
        this.subtopicsIdsubtopics = subtopicsIdsubtopics;
    }
    public Questions(String question, String answer1, String answer2, String answer3, String answer4, Boolean correctAnswer, int topicsIdTopic, int topicsModulesIdModule, int subtopicsIdsubtopics) {
       this.question = question;
       this.answer1 = answer1;
       this.answer2 = answer2;
       this.answer3 = answer3;
       this.answer4 = answer4;
       this.correctAnswer = correctAnswer;
       this.topicsIdTopic = topicsIdTopic;
       this.topicsModulesIdModule = topicsModulesIdModule;
       this.subtopicsIdsubtopics = subtopicsIdsubtopics;
    }
   
    public Integer getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(Integer idQuestion) {
        this.idQuestion = idQuestion;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer1() {
        return this.answer1;
    }
    
    public void setAnswer1(String answer1) {
        this.answer1 = answer1;
    }
    public String getAnswer2() {
        return this.answer2;
    }
    
    public void setAnswer2(String answer2) {
        this.answer2 = answer2;
    }
    public String getAnswer3() {
        return this.answer3;
    }
    
    public void setAnswer3(String answer3) {
        this.answer3 = answer3;
    }
    public String getAnswer4() {
        return this.answer4;
    }
    
    public void setAnswer4(String answer4) {
        this.answer4 = answer4;
    }
    public Boolean getCorrectAnswer() {
        return this.correctAnswer;
    }
    
    public void setCorrectAnswer(Boolean correctAnswer) {
        this.correctAnswer = correctAnswer;
    }
    public int getTopicsIdTopic() {
        return this.topicsIdTopic;
    }
    
    public void setTopicsIdTopic(int topicsIdTopic) {
        this.topicsIdTopic = topicsIdTopic;
    }
    public int getTopicsModulesIdModule() {
        return this.topicsModulesIdModule;
    }
    
    public void setTopicsModulesIdModule(int topicsModulesIdModule) {
        this.topicsModulesIdModule = topicsModulesIdModule;
    }
    public int getSubtopicsIdsubtopics() {
        return this.subtopicsIdsubtopics;
    }
    
    public void setSubtopicsIdsubtopics(int subtopicsIdsubtopics) {
        this.subtopicsIdsubtopics = subtopicsIdsubtopics;
    }




}


