package com.generation.beans;
// Generated 9/09/2018 04:34:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private Integer idQuestion;
     private Subtopics subtopics;
     private String question;
     private String answer1;
     private String answer2;
     private String answer3;
     private String answer4;
     private Boolean correctAnswer;
     private Set userses = new HashSet(0);

    public Questions() {
    }

	
    public Questions(Subtopics subtopics) {
        this.subtopics = subtopics;
    }
    public Questions(Subtopics subtopics, String question, String answer1, String answer2, String answer3, String answer4, Boolean correctAnswer, Set userses) {
       this.subtopics = subtopics;
       this.question = question;
       this.answer1 = answer1;
       this.answer2 = answer2;
       this.answer3 = answer3;
       this.answer4 = answer4;
       this.correctAnswer = correctAnswer;
       this.userses = userses;
    }
   
    public Integer getIdQuestion() {
        return this.idQuestion;
    }
    
    public void setIdQuestion(Integer idQuestion) {
        this.idQuestion = idQuestion;
    }
    public Subtopics getSubtopics() {
        return this.subtopics;
    }
    
    public void setSubtopics(Subtopics subtopics) {
        this.subtopics = subtopics;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer1() {
        return this.answer1;
    }
    
    public void setAnswer1(String answer1) {
        this.answer1 = answer1;
    }
    public String getAnswer2() {
        return this.answer2;
    }
    
    public void setAnswer2(String answer2) {
        this.answer2 = answer2;
    }
    public String getAnswer3() {
        return this.answer3;
    }
    
    public void setAnswer3(String answer3) {
        this.answer3 = answer3;
    }
    public String getAnswer4() {
        return this.answer4;
    }
    
    public void setAnswer4(String answer4) {
        this.answer4 = answer4;
    }
    public Boolean getCorrectAnswer() {
        return this.correctAnswer;
    }
    
    public void setCorrectAnswer(Boolean correctAnswer) {
        this.correctAnswer = correctAnswer;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }

    @Override
    public String toString() {
        return "Questions{" + "idQuestion=" + idQuestion + ", subtopics=" + subtopics + ", question=" + question + ", answer1=" + answer1 + ", answer2=" + answer2 + ", answer3=" + answer3 + ", answer4=" + answer4 + ", correctAnswer=" + correctAnswer + ", userses=" + userses + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.idQuestion);
        hash = 23 * hash + Objects.hashCode(this.subtopics);
        hash = 23 * hash + Objects.hashCode(this.question);
        hash = 23 * hash + Objects.hashCode(this.answer1);
        hash = 23 * hash + Objects.hashCode(this.answer2);
        hash = 23 * hash + Objects.hashCode(this.answer3);
        hash = 23 * hash + Objects.hashCode(this.answer4);
        hash = 23 * hash + Objects.hashCode(this.correctAnswer);
        hash = 23 * hash + Objects.hashCode(this.userses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Questions other = (Questions) obj;
        if (!Objects.equals(this.question, other.question)) {
            return false;
        }
        if (!Objects.equals(this.answer1, other.answer1)) {
            return false;
        }
        if (!Objects.equals(this.answer2, other.answer2)) {
            return false;
        }
        if (!Objects.equals(this.answer3, other.answer3)) {
            return false;
        }
        if (!Objects.equals(this.answer4, other.answer4)) {
            return false;
        }
        if (!Objects.equals(this.idQuestion, other.idQuestion)) {
            return false;
        }
        if (!Objects.equals(this.subtopics, other.subtopics)) {
            return false;
        }
        if (!Objects.equals(this.correctAnswer, other.correctAnswer)) {
            return false;
        }
        if (!Objects.equals(this.userses, other.userses)) {
            return false;
        }
        return true;
    }

    


}


