package com.generation.beans;
// Generated 9/09/2018 04:34:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Subtopics generated by hbm2java
 */
public class Subtopics  implements java.io.Serializable {


     private Integer idsubtopics;
     private Topics topics;
     private String nombreSubtopic;
     private Set questionses = new HashSet(0);

    public Subtopics() {
    }

	
    public Subtopics(Topics topics) {
        this.topics = topics;
    }
    public Subtopics(Topics topics, String nombreSubtopic, Set questionses) {
       this.topics = topics;
       this.nombreSubtopic = nombreSubtopic;
       this.questionses = questionses;
    }
   
    public Integer getIdsubtopics() {
        return this.idsubtopics;
    }
    
    public void setIdsubtopics(Integer idsubtopics) {
        this.idsubtopics = idsubtopics;
    }
    public Topics getTopics() {
        return this.topics;
    }
    
    public void setTopics(Topics topics) {
        this.topics = topics;
    }
    public String getNombreSubtopic() {
        return this.nombreSubtopic;
    }
    
    public void setNombreSubtopic(String nombreSubtopic) {
        this.nombreSubtopic = nombreSubtopic;
    }
    public Set getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set questionses) {
        this.questionses = questionses;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.idsubtopics);
        hash = 79 * hash + Objects.hashCode(this.topics);
        hash = 79 * hash + Objects.hashCode(this.nombreSubtopic);
        hash = 79 * hash + Objects.hashCode(this.questionses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Subtopics other = (Subtopics) obj;
        if (!Objects.equals(this.nombreSubtopic, other.nombreSubtopic)) {
            return false;
        }
        if (!Objects.equals(this.idsubtopics, other.idsubtopics)) {
            return false;
        }
        if (!Objects.equals(this.topics, other.topics)) {
            return false;
        }
        if (!Objects.equals(this.questionses, other.questionses)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Subtopics{" + "idsubtopics=" + idsubtopics + ", topics=" + topics + ", nombreSubtopic=" + nombreSubtopic + ", questionses=" + questionses + '}';
    }

    


}


