package com.generation.beans;
// Generated 9/09/2018 04:34:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subtopics generated by hbm2java
 */
public class Subtopics  implements java.io.Serializable {


     private Integer idsubtopics;
     private Topics topics;
     private String nombreSubtopic;
     private Set questionses = new HashSet(0);

    public Subtopics() {
    }

	
    public Subtopics(Topics topics) {
        this.topics = topics;
    }
    public Subtopics(Topics topics, String nombreSubtopic, Set questionses) {
       this.topics = topics;
       this.nombreSubtopic = nombreSubtopic;
       this.questionses = questionses;
    }
   
    public Integer getIdsubtopics() {
        return this.idsubtopics;
    }
    
    public void setIdsubtopics(Integer idsubtopics) {
        this.idsubtopics = idsubtopics;
    }
    public Topics getTopics() {
        return this.topics;
    }
    
    public void setTopics(Topics topics) {
        this.topics = topics;
    }
    public String getNombreSubtopic() {
        return this.nombreSubtopic;
    }
    
    public void setNombreSubtopic(String nombreSubtopic) {
        this.nombreSubtopic = nombreSubtopic;
    }
    public Set getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set questionses) {
        this.questionses = questionses;
    }




}


