package com.generation.beans;
// Generated 8/09/2018 07:09:43 PM by Hibernate Tools 4.3.1



/**
 * Subtopics generated by hbm2java
 */
public class Subtopics  implements java.io.Serializable {


     private Integer idsubtopics;
     private String nombreSubtopic;
     private int topicsIdTopic;

    public Subtopics() {
    }

	
    public Subtopics(int topicsIdTopic) {
        this.topicsIdTopic = topicsIdTopic;
    }
    public Subtopics(String nombreSubtopic, int topicsIdTopic) {
       this.nombreSubtopic = nombreSubtopic;
       this.topicsIdTopic = topicsIdTopic;
    }
   
    public Integer getIdsubtopics() {
        return this.idsubtopics;
    }
    
    public void setIdsubtopics(Integer idsubtopics) {
        this.idsubtopics = idsubtopics;
    }
    public String getNombreSubtopic() {
        return this.nombreSubtopic;
    }
    
    public void setNombreSubtopic(String nombreSubtopic) {
        this.nombreSubtopic = nombreSubtopic;
    }
    public int getTopicsIdTopic() {
        return this.topicsIdTopic;
    }
    
    public void setTopicsIdTopic(int topicsIdTopic) {
        this.topicsIdTopic = topicsIdTopic;
    }




}


