package com.generation.beans;
// Generated 8/09/2018 07:09:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tokens generated by hbm2java
 */
public class Tokens  implements java.io.Serializable {


     private Integer idToken;
     private String token;
     private Date date;
     private String status;
     private Boolean tokenscol;
     private String key;
     private String turn;
     private int usersIdUser;

    public Tokens() {
    }

	
    public Tokens(int usersIdUser) {
        this.usersIdUser = usersIdUser;
    }
    public Tokens(String token, Date date, String status, Boolean tokenscol, String key, String turn, int usersIdUser) {
       this.token = token;
       this.date = date;
       this.status = status;
       this.tokenscol = tokenscol;
       this.key = key;
       this.turn = turn;
       this.usersIdUser = usersIdUser;
    }
   
    public Integer getIdToken() {
        return this.idToken;
    }
    
    public void setIdToken(Integer idToken) {
        this.idToken = idToken;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Boolean getTokenscol() {
        return this.tokenscol;
    }
    
    public void setTokenscol(Boolean tokenscol) {
        this.tokenscol = tokenscol;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getTurn() {
        return this.turn;
    }
    
    public void setTurn(String turn) {
        this.turn = turn;
    }
    public int getUsersIdUser() {
        return this.usersIdUser;
    }
    
    public void setUsersIdUser(int usersIdUser) {
        this.usersIdUser = usersIdUser;
    }




}


