package com.generation.beans;
// Generated 9/09/2018 04:34:06 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tokens generated by hbm2java
 */
public class Tokens  implements java.io.Serializable {


     private Integer idToken;
     private Users users;
     private String token;
     private Date date;
     private Integer status;
     private String key;
     private String turn;

    public Tokens() {
    }

	
    public Tokens(Users users) {
        this.users = users;
    }
    public Tokens(Users users, String token, Date date, Integer status, String key, String turn) {
       this.users = users;
       this.token = token;
       this.date = date;
       this.status = status;
       this.key = key;
       this.turn = turn;
    }
   
    public Integer getIdToken() {
        return this.idToken;
    }
    
    public void setIdToken(Integer idToken) {
        this.idToken = idToken;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getTurn() {
        return this.turn;
    }
    
    public void setTurn(String turn) {
        this.turn = turn;
    }




}


