package com.generation.beans;
// Generated 24/09/2018 11:42:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token  implements java.io.Serializable {


     private Integer idToken;
     private User user;
     private String token;
     private Date date;
     private String status;
     private String keyt;
     private String turn;

    public Token() {
    }

	
    public Token(User user) {
        this.user = user;
    }
    public Token(User user, String token, Date date, String status, String keyt, String turn) {
       this.user = user;
       this.token = token;
       this.date = date;
       this.status = status;
       this.keyt = keyt;
       this.turn = turn;
    }
   
    public Integer getIdToken() {
        return this.idToken;
    }
    
    public void setIdToken(Integer idToken) {
        this.idToken = idToken;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getKeyt() {
        return this.keyt;
    }
    
    public void setKeyt(String keyt) {
        this.keyt = keyt;
    }
    public String getTurn() {
        return this.turn;
    }
    
    public void setTurn(String turn) {
        this.turn = turn;
    }




}


