package com.generation.beans;
// Generated 9/09/2018 04:34:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Topics generated by hbm2java
 */
public class Topics  implements java.io.Serializable {


     private Integer idTopic;
     private Modules modules;
     private String nombreTopic;
     private Set subtopicses = new HashSet(0);

    public Topics() {
    }

	
    public Topics(Modules modules) {
        this.modules = modules;
    }
    public Topics(Modules modules, String nombreTopic, Set subtopicses) {
       this.modules = modules;
       this.nombreTopic = nombreTopic;
       this.subtopicses = subtopicses;
    }
   
    public Integer getIdTopic() {
        return this.idTopic;
    }
    
    public void setIdTopic(Integer idTopic) {
        this.idTopic = idTopic;
    }
    public Modules getModules() {
        return this.modules;
    }
    
    public void setModules(Modules modules) {
        this.modules = modules;
    }
    public String getNombreTopic() {
        return this.nombreTopic;
    }
    
    public void setNombreTopic(String nombreTopic) {
        this.nombreTopic = nombreTopic;
    }
    public Set getSubtopicses() {
        return this.subtopicses;
    }
    
    public void setSubtopicses(Set subtopicses) {
        this.subtopicses = subtopicses;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.idTopic);
        hash = 89 * hash + Objects.hashCode(this.modules);
        hash = 89 * hash + Objects.hashCode(this.nombreTopic);
        hash = 89 * hash + Objects.hashCode(this.subtopicses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Topics other = (Topics) obj;
        if (!Objects.equals(this.nombreTopic, other.nombreTopic)) {
            return false;
        }
        if (!Objects.equals(this.idTopic, other.idTopic)) {
            return false;
        }
        if (!Objects.equals(this.modules, other.modules)) {
            return false;
        }
        if (!Objects.equals(this.subtopicses, other.subtopicses)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Topics{" + "idTopic=" + idTopic + ", modules=" + modules + ", nombreTopic=" + nombreTopic + ", subtopicses=" + subtopicses + '}';
    }

    



}


