package com.generation.beans;
// Generated 24/09/2018 11:42:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String mail;
     private String pass;
     private String userscol;
     private String nick;
     private Integer userStatus;
     private Set tokens = new HashSet(0);
     private Set questions = new HashSet(0);

    public User() {
    }

    public User(String mail, String pass, String userscol, String nick, Integer userStatus, Set tokens, Set questions) {
       this.mail = mail;
       this.pass = pass;
       this.userscol = userscol;
       this.nick = nick;
       this.userStatus = userStatus;
       this.tokens = tokens;
       this.questions = questions;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getUserscol() {
        return this.userscol;
    }
    
    public void setUserscol(String userscol) {
        this.userscol = userscol;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public Integer getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
    public Set getTokens() {
        return this.tokens;
    }
    
    public void setTokens(Set tokens) {
        this.tokens = tokens;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


