package com.generation.beans;
// Generated 8/09/2018 07:09:43 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String mail;
     private String pass;
     private String userscol;
     private String nick;

    public Users() {
    }

    public Users(String mail, String pass, String userscol, String nick) {
       this.mail = mail;
       this.pass = pass;
       this.userscol = userscol;
       this.nick = nick;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getUserscol() {
        return this.userscol;
    }
    
    public void setUserscol(String userscol) {
        this.userscol = userscol;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }




}


