package com.generation.beans;
// Generated 24/09/2018 11:42:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * WrongAnswer generated by hbm2java
 */
public class WrongAnswer  implements java.io.Serializable {


     private int idwrongAnswer;
     private String wrongAnswer;
     private Integer wrongAnswerStatus;
     private Set questions = new HashSet(0);

    public WrongAnswer() {
    }

	
    public WrongAnswer(int idwrongAnswer) {
        this.idwrongAnswer = idwrongAnswer;
    }
    public WrongAnswer(int idwrongAnswer, String wrongAnswer, Integer wrongAnswerStatus, Set questions) {
       this.idwrongAnswer = idwrongAnswer;
       this.wrongAnswer = wrongAnswer;
       this.wrongAnswerStatus = wrongAnswerStatus;
       this.questions = questions;
    }
   
    public int getIdwrongAnswer() {
        return this.idwrongAnswer;
    }
    
    public void setIdwrongAnswer(int idwrongAnswer) {
        this.idwrongAnswer = idwrongAnswer;
    }
    public String getWrongAnswer() {
        return this.wrongAnswer;
    }
    
    public void setWrongAnswer(String wrongAnswer) {
        this.wrongAnswer = wrongAnswer;
    }
    public Integer getWrongAnswerStatus() {
        return this.wrongAnswerStatus;
    }
    
    public void setWrongAnswerStatus(Integer wrongAnswerStatus) {
        this.wrongAnswerStatus = wrongAnswerStatus;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


